// Sample data for the chickens
export const chickensData = [
  {
    id: 1,
    name: 'Henrietta',
    breed: 'Rhode Island Red',
    age: 2,
    weight: 1.8,
    eggProduction: 280,
  },
  {
    id: 2,
    name: 'Gertie',
    breed: 'Plymouth Rock',
    age: 1.5,
    weight: 2.1,
    eggProduction: 260,
  },
  {
    id: 3,
    name: 'Peggy',
    breed: 'Leghorn',
    age: 3,
    weight: 1.6,
    eggProduction: 300,
  },
  {
    id: 4,
    name: 'Hattie',
    breed: 'Australorp',
    age: 2.5,
    weight: 2.3,
    eggProduction: 250,
  },
  {
    id: 5,
    name: 'Mabel',
    breed: 'Orpington',
    age: 1,
    weight: 2.5,
    eggProduction: 220,
  },
  {
    id: 6,
    name: 'Clara',
    breed: 'Silkie',
    age: 1.2,
    weight: 1.5,
    eggProduction: 180,
  },
  {
    id: 7,
    name: 'Daisy',
    breed: 'Cochin',
    age: 2.1,
    weight: 2.0,
    eggProduction: 200,
  },
  {
    id: 8,
    name: 'Lola',
    breed: 'Brahma',
    age: 3.5,
    weight: 2.8,
    eggProduction: 220,
  },
  {
    id: 9,
    name: 'Nina',
    breed: 'Sussex',
    age: 1.8,
    weight: 2.2,
    eggProduction: 240,
  },
  {
    id: 10,
    name: 'Ruby',
    breed: 'Wyandotte',
    age: 2.3,
    weight: 2.4,
    eggProduction: 260,
  },
  {
    id: 11,
    name: 'Sophie',
    breed: 'Marans',
    age: 1.7,
    weight: 2.1,
    eggProduction: 230,
  },
  {
    id: 12,
    name: 'Tilly',
    breed: 'Ancona',
    age: 2.9,
    weight: 1.9,
    eggProduction: 250,
  },
  {
    id: 13,
    name: 'Zelda',
    breed: 'Hamburg',
    age: 1.4,
    weight: 1.7,
    eggProduction: 190,
  },
  {
    id: 14,
    name: 'Penny',
    breed: 'Faverolles',
    age: 3.1,
    weight: 2.3,
    eggProduction: 210,
  },
  {
    id: 15,
    name: 'Molly',
    breed: 'Pekin',
    age: 2.6,
    weight: 2.6,
    eggProduction: 240,
  },
  {
    id: 16,
    name: 'Ella',
    breed: 'Campine',
    age: 1.9,
    weight: 1.8,
    eggProduction: 200,
  },
  {
    id: 17,
    name: 'Ginger',
    breed: 'Dorking',
    age: 2.4,
    weight: 2.5,
    eggProduction: 220,
  },
  {
    id: 18,
    name: 'Bella',
    breed: 'Orpington',
    age: 1.3,
    weight: 2.4,
    eggProduction: 250,
  },
  {
    id: 19,
    name: 'Chloe',
    breed: 'Langshan',
    age: 2.8,
    weight: 2.2,
    eggProduction: 230,
  },
  {
    id: 20,
    name: 'Luna',
    breed: 'Croad Langshan',
    age: 1.6,
    weight: 2.0,
    eggProduction: 210,
  },
  {
    id: 21,
    name: 'Daisy',
    breed: 'Sussex',
    age: 2.1,
    weight: 2.3,
    eggProduction: 240,
  },
  {
    id: 22,
    name: 'Ruby',
    breed: 'Brahma',
    age: 3.0,
    weight: 2.8,
    eggProduction: 210,
  },
  {
    id: 23,
    name: 'Nina',
    breed: 'Cochin',
    age: 1.5,
    weight: 2.4,
    eggProduction: 220,
  },
  {
    id: 24,
    name: 'Sophie',
    breed: 'Silkie',
    age: 2.2,
    weight: 1.9,
    eggProduction: 180,
  },
  {
    id: 25,
    name: 'Lily',
    breed: 'Wyandotte',
    age: 1.8,
    weight: 2.5,
    eggProduction: 250,
  },
  {
    id: 26,
    name: 'Penny',
    breed: 'Faverolles',
    age: 2.5,
    weight: 2.2,
    eggProduction: 230,
  },
  {
    id: 27,
    name: 'Zoe',
    breed: 'Hamburg',
    age: 1.7,
    weight: 1.7,
    eggProduction: 200,
  },
  {
    id: 28,
    name: 'Maggie',
    breed: 'Marans',
    age: 2.9,
    weight: 2.6,
    eggProduction: 240,
  },
  {
    id: 29,
    name: 'Tina',
    breed: 'Plymouth Rock',
    age: 1.4,
    weight: 2.1,
    eggProduction: 260,
  },
  {
    id: 30,
    name: 'Coco',
    breed: 'Rhode Island Red',
    age: 2.3,
    weight: 2.0,
    eggProduction: 280,
  },
  {
    id: 31,
    name: 'Lola',
    breed: 'Leghorn',
    age: 1.2,
    weight: 1.5,
    eggProduction: 300,
  },
  {
    id: 32,
    name: 'Piper',
    breed: 'Orpington',
    age: 2.0,
    weight: 2.4,
    eggProduction: 250,
  },
  {
    id: 33,
    name: 'Roxy',
    breed: 'Australorp',
    age: 1.6,
    weight: 2.3,
    eggProduction: 240,
  },
  {
    id: 34,
    name: 'Dolly',
    breed: 'Croad Langshan',
    age: 2.7,
    weight: 2.5,
    eggProduction: 220,
  },
  {
    id: 35,
    name: 'Misty',
    breed: 'Langshan',
    age: 1.9,
    weight: 2.2,
    eggProduction: 230,
  },
  {
    id: 36,
    name: 'Gigi',
    breed: 'Dorking',
    age: 2.4,
    weight: 2.6,
    eggProduction: 210,
  },
  {
    id: 37,
    name: 'Fiona',
    breed: 'Campine',
    age: 1.8,
    weight: 1.9,
    eggProduction: 200,
  },
  {
    id: 38,
    name: 'Tilly',
    breed: 'Brahma',
    age: 2.2,
    weight: 2.7,
    eggProduction: 240,
  },
  {
    id: 39,
    name: 'Ella',
    breed: 'Sussex',
    age: 1.5,
    weight: 2.3,
    eggProduction: 250,
  },
  {
    id: 40,
    name: 'Chester',
    breed: 'Silkie',
    age: 2.1,
    weight: 1.8,
    eggProduction: 180,
  },
  {
    id: 41,
    name: 'Daisy',
    breed: 'Cochin',
    age: 1.7,
    weight: 2.4,
    eggProduction: 260,
  },
  {
    id: 42,
    name: 'Lola',
    breed: 'Plymouth Rock',
    age: 2.5,
    weight: 2.0,
    eggProduction: 270,
  },
  {
    id: 43,
    name: 'Ruby',
    breed: 'Rhode Island Red',
    age: 3.0,
    weight: 1.9,
    eggProduction: 290,
  },
  {
    id: 44,
    name: 'Nina',
    breed: 'Leghorn',
    age: 1.8,
    weight: 1.7,
    eggProduction: 300,
  },
  {
    id: 45,
    name: 'Sophie',
    breed: 'Orpington',
    age: 2.3,
    weight: 2.5,
    eggProduction: 280,
  },
  {
    id: 46,
    name: 'Bella',
    breed: 'Australorp',
    age: 1.6,
    weight: 2.1,
    eggProduction: 250,
  },
  {
    id: 47,
    name: 'Maggie',
    breed: 'Silkie',
    age: 2.0,
    weight: 1.8,
    eggProduction: 220,
  },
  {
    id: 48,
    name: 'Penny',
    breed: 'Croad Langshan',
    age: 1.9,
    weight: 2.3,
    eggProduction: 240,
  },
  {
    id: 49,
    name: 'Zoe',
    breed: 'Dorking',
    age: 2.1,
    weight: 2.4,
    eggProduction: 210,
  },
  {
    id: 50,
    name: 'Luna',
    breed: 'Campine',
    age: 1.5,
    weight: 1.6,
    eggProduction: 230,
  },
  {
    id: 51,
    name: 'Coco',
    breed: 'Brahma',
    age: 2.4,
    weight: 2.8,
    eggProduction: 260,
  },
  {
    id: 52,
    name: 'Misty',
    breed: 'Sussex',
    age: 1.7,
    weight: 2.2,
    eggProduction: 240,
  },
  {
    id: 53,
    name: 'Ginger',
    breed: 'Langshan',
    age: 2.2,
    weight: 2.5,
    eggProduction: 250,
  },
  {
    id: 54,
    name: 'Chloe',
    breed: 'Plymouth Rock',
    age: 1.8,
    weight: 2.0,
    eggProduction: 270,
  },
  {
    id: 55,
    name: 'Dolly',
    breed: 'Rhode Island Red',
    age: 2.5,
    weight: 1.9,
    eggProduction: 290,
  },
  {
    id: 56,
    name: 'Tina',
    breed: 'Leghorn',
    age: 1.6,
    weight: 1.8,
    eggProduction: 300,
  },
  {
    id: 57,
    name: 'Fiona',
    breed: 'Orpington',
    age: 2.3,
    weight: 2.4,
    eggProduction: 280,
  },
  {
    id: 58,
    name: 'Ella',
    breed: 'Australorp',
    age: 1.9,
    weight: 2.1,
    eggProduction: 250,
  },
  {
    id: 59,
    name: 'Lily',
    breed: 'Silkie',
    age: 2.0,
    weight: 1.7,
    eggProduction: 220,
  },
  {
    id: 60,
    name: 'Mabel',
    breed: 'Croad Langshan',
    age: 1.8,
    weight: 2.3,
    eggProduction: 240,
  },
  {
    id: 61,
    name: 'Sandy',
    breed: 'Dorking',
    age: 2.1,
    weight: 2.6,
    eggProduction: 210,
  },
  {
    id: 62,
    name: 'Piper',
    breed: 'Campine',
    age: 1.5,
    weight: 1.9,
    eggProduction: 230,
  },
  {
    id: 63,
    name: 'Wendy',
    breed: 'Brahma',
    age: 2.4,
    weight: 2.7,
    eggProduction: 260,
  },
  {
    id: 64,
    name: 'Nora',
    breed: 'Sussex',
    age: 1.6,
    weight: 2.3,
    eggProduction: 240,
  },
  {
    id: 65,
    name: 'Cathy',
    breed: 'Langshan',
    age: 2.2,
    weight: 2.5,
    eggProduction: 250,
  },
  {
    id: 66,
    name: 'Rita',
    breed: 'Plymouth Rock',
    age: 1.9,
    weight: 2.0,
    eggProduction: 270,
  },
  {
    id: 67,
    name: 'Tessa',
    breed: 'Rhode Island Red',
    age: 2.5,
    weight: 1.9,
    eggProduction: 290,
  },
  {
    id: 68,
    name: 'Molly',
    breed: 'Leghorn',
    age: 1.8,
    weight: 1.7,
    eggProduction: 300,
  },
  {
    id: 69,
    name: 'Daisy',
    breed: 'Orpington',
    age: 2.3,
    weight: 2.5,
    eggProduction: 280,
  },
  {
    id: 70,
    name: 'Lola',
    breed: 'Australorp',
    age: 1.6,
    weight: 2.1,
    eggProduction: 250,
  },
  {
    id: 71,
    name: 'Ruby',
    breed: 'Silkie',
    age: 2.0,
    weight: 1.8,
    eggProduction: 220,
  },
  {
    id: 72,
    name: 'Penny',
    breed: 'Croad Langshan',
    age: 1.9,
    weight: 2.3,
    eggProduction: 240,
  },
  {
    id: 73,
    name: 'Zoe',
    breed: 'Dorking',
    age: 2.1,
    weight: 2.4,
    eggProduction: 210,
  },
  {
    id: 74,
    name: 'Luna',
    breed: 'Campine',
    age: 1.5,
    weight: 1.6,
    eggProduction: 230,
  },
  {
    id: 75,
    name: 'Coco',
    breed: 'Brahma',
    age: 2.4,
    weight: 2.8,
    eggProduction: 260,
  },
  {
    id: 76,
    name: 'Misty',
    breed: 'Sussex',
    age: 1.7,
    weight: 2.2,
    eggProduction: 240,
  },
  {
    id: 77,
    name: 'Ginger',
    breed: 'Langshan',
    age: 2.2,
    weight: 2.5,
    eggProduction: 250,
  },
  {
    id: 78,
    name: 'Chloe',
    breed: 'Plymouth Rock',
    age: 1.8,
    weight: 2.0,
    eggProduction: 270,
  },
  {
    id: 79,
    name: 'Dolly',
    breed: 'Rhode Island Red',
    age: 2.5,
    weight: 1.9,
    eggProduction: 290,
  },
  {
    id: 80,
    name: 'Tina',
    breed: 'Leghorn',
    age: 1.6,
    weight: 1.8,
    eggProduction: 300,
  },
  {
    id: 81,
    name: 'Fiona',
    breed: 'Orpington',
    age: 2.3,
    weight: 2.4,
    eggProduction: 280,
  },
  {
    id: 82,
    name: 'Ella',
    breed: 'Australorp',
    age: 1.9,
    weight: 2.1,
    eggProduction: 250,
  },
  {
    id: 83,
    name: 'Lily',
    breed: 'Silkie',
    age: 2.0,
    weight: 1.7,
    eggProduction: 220,
  },
  {
    id: 84,
    name: 'Mabel',
    breed: 'Croad Langshan',
    age: 1.8,
    weight: 2.3,
    eggProduction: 240,
  },
  {
    id: 85,
    name: 'Sandy',
    breed: 'Dorking',
    age: 2.1,
    weight: 2.6,
    eggProduction: 210,
  },
  {
    id: 86,
    name: 'Piper',
    breed: 'Campine',
    age: 1.5,
    weight: 1.9,
    eggProduction: 230,
  },
  {
    id: 87,
    name: 'Wendy',
    breed: 'Brahma',
    age: 2.4,
    weight: 2.7,
    eggProduction: 260,
  },
  {
    id: 88,
    name: 'Nora',
    breed: 'Sussex',
    age: 1.6,
    weight: 2.3,
    eggProduction: 240,
  },
  {
    id: 89,
    name: 'Cathy',
    breed: 'Langshan',
    age: 2.2,
    weight: 2.5,
    eggProduction: 250,
  },
  {
    id: 90,
    name: 'Rita',
    breed: 'Plymouth Rock',
    age: 1.9,
    weight: 2.0,
    eggProduction: 270,
  },
  {
    id: 91,
    name: 'Tessa',
    breed: 'Rhode Island Red',
    age: 2.5,
    weight: 1.9,
    eggProduction: 290,
  },
  {
    id: 92,
    name: 'Molly',
    breed: 'Leghorn',
    age: 1.8,
    weight: 1.7,
    eggProduction: 300,
  },
  {
    id: 93,
    name: 'Daisy',
    breed: 'Orpington',
    age: 2.3,
    weight: 2.5,
    eggProduction: 280,
  },
  {
    id: 94,
    name: 'Lola',
    breed: 'Australorp',
    age: 1.6,
    weight: 2.1,
    eggProduction: 250,
  },
  {
    id: 95,
    name: 'Ruby',
    breed: 'Silkie',
    age: 2.0,
    weight: 1.8,
    eggProduction: 220,
  },
  {
    id: 96,
    name: 'Penny',
    breed: 'Croad Langshan',
    age: 1.9,
    weight: 2.3,
    eggProduction: 240,
  },
  {
    id: 97,
    name: 'Zoe',
    breed: 'Dorking',
    age: 2.1,
    weight: 2.4,
    eggProduction: 210,
  },
  {
    id: 98,
    name: 'Luna',
    breed: 'Campine',
    age: 1.5,
    weight: 1.6,
    eggProduction: 230,
  },
  {
    id: 99,
    name: 'Coco',
    breed: 'Brahma',
    age: 2.4,
    weight: 2.8,
    eggProduction: 260,
  },
  {
    id: 100,
    name: 'Misty',
    breed: 'Sussex',
    age: 1.7,
    weight: 2.2,
    eggProduction: 240,
  },
];
